name: Auto Rebase Main to Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  rebase-branches:
    name: Rebase Main into Backend & Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for rebase

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Rebase master-backend onto main
        id: rebase_backend
        run: |
          git checkout master-backend
          git pull origin master-backend
          if git rebase main; then
            git push --force-with-lease origin master-backend
            echo "backend_conflict=false" >> $GITHUB_ENV
          else
            git rebase --abort
            echo "backend_conflict=true" >> $GITHUB_ENV
          fi

      - name: Create PR for master-backend if conflicts exist
        if: env.backend_conflict == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          base: master-backend
          head: main
          title: "Resolve conflicts: Rebase main onto master-backend"
          body: "Conflicts detected during rebase. Resolve manually."
          labels: "auto-rebase"

      - name: Rebase master-frontend onto main
        id: rebase_frontend
        run: |
          git checkout master-frontend
          git pull origin master-frontend
          if git rebase main; then
            git push --force-with-lease origin master-frontend
            echo "frontend_conflict=false" >> $GITHUB_ENV
          else
            git rebase --abort
            echo "frontend_conflict=true" >> $GITHUB_ENV
          fi

      - name: Create PR for master-frontend if conflicts exist
        if: env.frontend_conflict == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          base: master-frontend
          head: main
          title: "Resolve conflicts: Rebase main onto master-frontend"
          body: "Conflicts detected during rebase. Resolve manually."
          labels: "auto-rebase"
