name: Auto Merge Main to Backend & Frontend

on:
  push:
    branches:
      - main

jobs:
  merge-branches:
    name: Merge Main into Backend & Frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for merge

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge Main into master-backend (Fast-Forward Only)
        id: merge_backend
        run: |
          git checkout master-backend
          if ! git merge --ff-only main; then
            echo "conflict=true" >> $GITHUB_ENV
          fi

      - name: Push Fast-Forward Merge to master-backend
        if: env.conflict != 'true'
        run: git push origin master-backend

      - name: Create PR for master-backend if conflicts exist
        if: env.conflict == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          base: master-backend
          head: main
          title: "Resolve conflicts: Merge main into master-backend"
          body: "Conflicts detected. Resolve manually."
          labels: "auto-merge"

      - name: Merge Main into master-frontend (Fast-Forward Only)
        id: merge_frontend
        run: |
          git checkout master-frontend
          if ! git merge --ff-only main; then
            echo "conflict=true" >> $GITHUB_ENV
          fi

      - name: Push Fast-Forward Merge to master-frontend
        if: env.conflict != 'true'
        run: git push origin master-frontend

      - name: Create PR for master-frontend if conflicts exist
        if: env.conflict == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          base: master-frontend
          head: main
          title: "Resolve conflicts: Merge main into master-frontend"
          body: "Conflicts detected. Resolve manually."
          labels: "auto-merge"
