name: Check Branch Sync and Conditional Auto-Merge

on:
  push:
    branches:
      - main  # Runs every time main is updated

jobs:
  check-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for comparisons

      - name: Check if master-backend is behind main
        id: backend_check
        run: |
          git fetch --all
          if git merge-base --is-ancestor main origin/master-backend; then
            echo "backend_up_to_date=true" >> $GITHUB_ENV
          else
            echo "backend_up_to_date=false" >> $GITHUB_ENV
          fi

      - name: Check if master-frontend is behind main
        id: frontend_check
        run: |
          git fetch --all
          if git merge-base --is-ancestor main origin/master-frontend; then
            echo "frontend_up_to_date=true" >> $GITHUB_ENV
          else
            echo "frontend_up_to_date=false" >> $GITHUB_ENV
          fi

  update-branches:
    needs: check-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge main into master-backend (if needed)
        if: env.backend_up_to_date == 'false'
        run: |
          git fetch --all
          git checkout master-backend
          git merge origin/main --no-edit || echo "CONFLICT=true" >> $GITHUB_ENV
          if [[ "$CONFLICT" != "true" ]]; then
            git push origin master-backend
          else
            gh pr create --base master-backend --head main --title "Sync main -> master-backend" --body "Conflicts detected – manual merge required."
          fi

      - name: Merge main into master-frontend (if needed)
        if: env.frontend_up_to_date == 'false'
        run: |
          git fetch --all
          git checkout master-frontend
          git merge origin/main --no-edit || echo "CONFLICT=true" >> $GITHUB_ENV
          if [[ "$CONFLICT" != "true" ]]; then
            git push origin master-frontend
          else
            gh pr create --base master-frontend --head main --title "Sync main -> master-frontend" --body "Conflicts detected – manual merge required."
          fi

      - name: Enable Auto-Merge (if no conflicts)
        if: env.CONFLICT != 'true'
        run: |
          for pr in $(gh pr list --state open --json number --jq '.[].number'); do
            gh pr merge $pr --auto --squash
          done
